config/routes.rb
Rails.application.routes.draw do
  root to: "searches#home"

  post "search_submitted", to: "searches#search_submitted"
  get "save_incomplete_searches", to: "searches#save_incomplete_searches"

  get "search_dashbord_analytics", to: "dashboard#dashbord_analytics"
  get "clear_search_analytics", to: "dashboard#clear_search_analytics"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  before_save :downcase_and_strip

  def downcase_and_strip
    self.term = self.term.downcase.strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #this could be a separated service/app so we could have space for horizontal scale.
  def dashbord_analytics
    @good_analytics = Search.where(
      submitted: true).group(:term).order('count_term desc').count(:term)
    @bad_analytics = Search.where(
      submitted: false).group(:term).order('count_term desc').count(:term)
  end


  def clear_search_analytics
    Search.destroy_all

    render :dashbord_analytics
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def home
    @search = Search.new

    gon.save_incomplete_searches_url = save_incomplete_searches_path
  end

  #this could be a separated service/app so we could have space for horizontal scale.
  def save_incomplete_searches
    if params[:term].present?
      search = Search.new(term: params[:term])
      search.save

      #this could be a separated service/app so we could have space for horizontal scale.
      #this is only a optional return that we could use if this project had real articles,
      #something that could make easier for the user find what he is searching for.
      search_result = ["Just a Sample Article", "Another Sample Article"]
    end

    render json: search_result
  end


  def search_submitted
    if search_params[:term].present?
      search = Search.new(term: search_params[:term], submitted: true)
      search.save
    end

    redirect_to :root
  end


  private

    def search_params
      params.require(:search).permit(:term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def list_of_searches(list)
    if list.present?
      render partial: "search_list", locals: { list: list }
    else
      "No search was performed."
    end
  end
end

app/views/dashboard/_search_list.html.erb
<ol>
  <% list.each do |search| %>
    <li><%= "#{search[0]} (#{search[1]} searches)" %></li>
  <% end %>
</ol>

app/views/dashboard/dashbord_analytics.html.erb
<h1 align="center" class="search-page-head-title"><%= t('analytical.page-title') %></h1>

<div class="search_box_head head-color-analytics" align="center">
  <div>
    <h2><%= t('analytical.list-box.head-title') %></h2>
  </div>
</div>

<div class="search_box_analytics">

  <div class="search_box_content_analytics">

    <div class="search_box_analytics_list">
      <h3><%= t('analytical.list-box.good-list-title') %></h3>
      <%= list_of_searches(@good_analytics) %>

      <h3><%= t('analytical.list-box.bad-list-title') %></h3>
      <%= list_of_searches(@bad_analytics) %>
    </div>

    <div>
      <p><%= button_to t('analytical.list-box.home-button'), root_path, class: "home button", method: :get %></p>
    </div>

    <div>
      <p>
        <%= button_to t('analytical.list-box.clear-button'), clear_search_analytics_path, class: "clear button",
          method: :get, data: { confirm: t('analytical.list-box.clear-button-confirmation') } %>
      </p>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuiceTest</title>
    <%= csrf_meta_tags %>
    <%= Gon::Base.render_data %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/home.html.erb
<h1 align="center" class="search-page-head-title"><%= t('home.page-title') %></h1>

<div class="search_box_head head-color" align="center">
  <div>
    <h2><%= t('home.search-box.head-title') %></h2>
  </div>
</div>

<div class="search_box">
  <div class="search_box_content">
    <%= form_for(@search, url: search_submitted_path) do |f| %>

      <label class="search_box_content_label">
        <%= t('home.search-box.input-label') %>
      </label> <br>
      <%= f.text_field :term, class: "search_box_content_input" %> <br>

      <span class="search_box_content_friendly_message">
        <%= t('home.search-box.friendly-message') %>
      </span> <br>

      <div>
        <p><%= f.submit t('home.search-box.submit-button'), class: "get_help button" %></p>
      </div>
    <% end %>

    <div>
      <p>
        <%= button_to t('home.search-box.dashboard-button'), search_dashbord_analytics_path,
          class: "dashboard button", method: :get %>
      </p>
    </div>

  </div>
</div>